apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: prober
  name: prober
  namespace: {{ .Release.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: prober
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prober
    spec:
      containers:
        - command:
            - ./main
          image: localhost:5001/poller:v1.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              port: 8080
              path: liveness
            timeoutSeconds: 5
          name: prober
          readinessProbe:
            httpGet:
              port: 8080
              path: readiness
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "1"
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 32Mi
          env:
            - name: GOMAXPROCS
              value: "8" # my machine has 8 cores and Orbstack uses all of them.
            - name: END_POINT
              value: "http://frontend-podinfo.{{ .Release.Namespace }}:9898/"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30